server:
  port: 8080
  servlet:
    context-path: /api/v1/travel-checker
    application-display-name: 'Travel Checker API'
spring:
  application:
    name: travel-checker-server
  jpa:
    open-in-view: true
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  profiles:
    active: dev
luv2code:
  travel-checker:
    mapbox:
      token: ${TRAVEL_CHECKER_MAPBOX_TOKEN}
    locale:
      baseName: classpath:messages
      defaultLocale: en
      defaultEncoding: UTF-8
    api-info:
      title: 'Travel Checker API'
      description: 'Spring Boot REST API for Travel Checker'
      version: '1.0.0'
      termsOfServiceUrl: 'https://github.com/lzugaj/travel-checker-server'
      name: 'Luka Zugaj'
      url: 'https://github.com/lzugaj'
      email: 'luka.zugaj7@gmail.com'
      license: 'Apache License Version 2.0'
      licenseUrl: 'https://www.apache.org/licenses/LICENSE-2.0'
    template-resolver:
      prefix: 'classpath:/templates/'
      suffix: '.html'
    message-helper:
      from: 'travel.checker@gmail.com'
      subject: 'Travel Checker'
      resetUrl: 'http://localhost:8080/api/v1/travel-checker/reset-password?token=$resetToken'
logging:
  file:
    path: logs
    name: server