spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: ${TRAVEL_CHECKER_DEV_DB_URL:jdbc:h2:file:C:/Workspace/travel-checker/travel-checker-server/src/main/resources/db/data/travelchecker;AUTO_SERVER=true} # jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: ${TRAVEL_CHECKER_DEV_DB_USERNAME:sa} #sa
    password: ${TRAVEL_CHECKER_DEV_DB_PASSWORD:password} #password
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  mail:
    host: 127.0.0.1
    port: 1025
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
