server:
  port: 8080
  servlet:
    context-path: /api/v1/travel-checker
spring:
  profiles:
    active: test
luv2code:
  travel-checker:
    mapbox:
      token: 'pk.eyJ1IjoibHp1Z2FqIiwiYSI6ImNrbHpnbGhvMjFraW0ybnBsdzR3OXN6bDAifQ.dBuHMH1r6dH22MsrXrCRUQ'