spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${TRAVEL_CHECKER_TEST_DB_URL}
    username: ${TRAVEL_CHECKER_TEST_DB_USERNAME}
    password: ${TRAVEL_CHECKER_TEST_DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml