spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb # ${TRAVEL_CHECKER_DEV_DB_URL}
    username: ${TRAVEL_CHECKER_DEV_DB_USERNAME}
    password: ${TRAVEL_CHECKER_DEV_DB_PASSWORD}
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml