spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/travel-checker-test'
    username: 'postgres'
    password: 'postgres'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: 127.0.0.1
    port: 1025
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
