version: '3'
services:
  backend:
    image: backend/backend
    container_name: backend
    build:
      context: ../..
    ports:
      - '9090:8080'
    depends_on:
      - db
    restart: always
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=travel-checker-test
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    logging:
      driver: none
    ports:
      - '1025:1025'
      - '8025:8025'
volumes:
  pgdata:
